[package]
name = "sai-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
chrono = "0.4.22"
eyre = "0.6.8"
lazy_static = "1.4.0"
tabular = "0.2.0"

[dependencies]
png = "0.17.6"
