[package]
name = "saire"
version = "0.3.0"
edition = "2021"

[lib]
name = "saire"
path = "src/lib.rs"

[[bin]]
name = "saire-cli"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = { version = "2.0.0", optional = true }
linked-hash-map = "0.5.6"
num-traits = "0.2.15"
png = { version = "0.17.6", optional = true }

[dev-dependencies]
chrono = "0.4.22"
eyre = "0.6.8"
lazy_static = "1.4.0"
tabular = "0.2.0"

[features]
default = ["png"]
png = ["dep:png"]
colored = ["dep:colored"]
